name = "friction"
version = "1.0.0"
license = "GPL-3.0"
author = "Jason Christopherson"
maintainer = "Jason Christopherson"
copyright = "Copyright 2024, Jason Christopherson"
description = "A library containing routines for calculating the frictional response of contacting bodies."
homepage = "https://github.com/jchristopherson/friction"

[library]
source-dir = "src"

[dependencies]
ferror = { git = "https://github.com/jchristopherson/ferror" }
diffeq = { git = "https://github.com/jchristopherson/diffeq" }
fitpack = { git = "https://github.com/jchristopherson/fitpack" }
fstats = { git = "https://github.com/jchristopherson/fstats" }

[dev-dependencies]
fortran_test_helper = { git = "https://github.com/jchristopherson/fortran_test_helper" }

[install]
library = true

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[[test]]
name = "friction_tests"
source-dir = "test"
main = "friction_test.f90"